Update example with async scheduler
when i use async import from 'rxjs/scheduler/async', show Error: Cannot find module 'rxjs-compat/Observable'.
So, I updated to import { async } from 'rxjs', it work~