use default sinon-chai import
namespace import is broken, and only worked because it's the same as default import in CJS code (require()).

error TS2345: Argument of type '{ default: ChaiPlugin; }' is not assignable to parameter of type 'ChaiPlugin'.
  Type '{ default: ChaiPlugin; }' provides no match for the signature '(chai: ChaiStatic, utils: ChaiUtils): void'.