docs(README): add missing import in example
Add a missing import statement for Observable.of. Without this fix, the
example code would generate an error message like
'Uncaught TypeError: _Observable.Observable.of is not a function(…)'
at runtime.